//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_5_Tutorials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        private Guid productId;

        public Guid GetProductId()
        {
            return productId;
        }

        public void SetProductId(Guid value)
        {
            productId = value;
        }

        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}
